version: "3.9"
services:
  docker-shezzy-frontend:
    build: .
    container_name: docker-shezzy-frontend
    image: docker-shezzy-frontend
    networks:
      - docker_shezzy_backend    
    ports:
      - "4026:80"      
    volumes:
      - /usr/share/nginx/html
      - /app/node_modules
    env_file: .env

networks:
  docker_shezzy_backend:
    name: docker_shezzy_backend
    driver: bridge     