version: "3.9"
services:
  docker-shezzy-frontend-stepper:
    build: .
    container_name: docker-shezzy-frontend-stepper
    image: docker-shezzy-frontend-stepper
    networks:
      - shezzy_frontend_stepper
    ports:
      - "4024:4024"      
    volumes:
      - /app
    env_file: .env
   