version: "3.9"
services:
  docker-benshez-router-frontend:
    build: .
    container_name: docker-benshez-router-frontend
    image: docker-benshez-router-frontend
    networks:
      - benshez_router_frontend    
    ports:
      - "5173:80"      
    volumes:
      - /usr/share/nginx/html
      - /app/node_modules
    env_file: .env

networks:
  benshez_router_frontend:
    name: benshez_router_frontend
    driver: bridge     